<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <AssemblyName>Tellurian.Utilities</AssemblyName>
	  <RootNamespace>Tellurian.Utilities</RootNamespace>
	  <Title>$(AssemblyName)</Title>
	  <PackageReadmeFile>README.md</PackageReadmeFile>
	  <PackageReleaseNotes>
		  Version 1.3.2
		  - IsDark added. Returns true if the color gives good contrast as background to white text.
	  </PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Markdig" Version="0.44.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
